### ISSUE TITLE
Language Bar at top

### ISSUE THREAD

**Issue by jazinheira** [saylordotorg/moodle-theme_saylor#11]
@sharmi55 Do we want a language drop-down taking space at the top? I'm worried it'll make it a bit TOO easy to change Moodle's language and students will think the course will change language as well. Thoughts?

<img width="951" alt="screen shot 2017-05-08 at 4 02 11 pm" src="https://cloud.githubusercontent.com/assets/6720891/25822806/e4e4e086-3407-11e7-8295-80959a183744.png">

**Comment by sharmi55** [comment]
- No, it's easier to manage if we give users less ability to personalize such things
- Still have that option but should be not easy to find.

**Comment by jazinheira** [comment]
Ok, able to remove that by unchecking "Display language menu" in "Language settings".

I've removed it from learn.saylor.org so we shouldn't have it show up in the future when we switch themes. Users are still able to change their language settings from their profile!

<img width="1008" alt="screen shot 2017-05-09 at 4 40 52 pm" src="https://cloud.githubusercontent.com/assets/6720891/25871759/91b0d8e6-34d6-11e7-994f-f776e80539df.png">
