### ISSUE TITLE
Registration/Enrollment Status

### ISSUE THREAD

**Issue by jazinheira** [saylordotorg/moodle-theme_saylor#12]
As per our UX study, students are having difficulty determining their enrollment status for a course and even registration/logged in status. We need to make this information more easily discernible.

@sharmi55 Let's use this as a dump/discussion ground for this enhancement.

**Comment by sharmi55** [comment]
- An easy and quick fix is to send an enrollment confirmation (working on a mockup after having analyzed several similar emails from our peers).

- Another would be to personalize the student dashboard by adding a greeting when logged in and when not logged in, inform user to log into their account or create account

- We could also improve the look of the registration confirmation email.
