### ISSUE TITLE
Image/text misaligned in question import dialog

### ISSUE THREAD

**Issue by athuggins** [saylordotorg/moodle-theme_saylor#148]
When importing new questions in bulk via the import questions dialog, the question mark images that describe each document format are misaligned with the text.

![screen shot 2019-01-07 at 11 37 31 am](https://user-images.githubusercontent.com/4674292/50792369-9021fc80-1279-11e9-8c2b-471acd050687.png)

I can't link directly due to how Moodle handles URLs, but you can see it by going to any course, then (edit menu gear icon) --> More... --> Question Bank/Import

**Comment by jazinheira** [comment]
Fixed in 3.6:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/6720891/51632315-fe72ea00-1f1c-11e9-9a5c-7b28f41a99b2.png">
