### ISSUE TITLE
Fix course overview font sizing in dashboard

### ISSUE THREAD

**Issue by jazinheira** [saylordotorg/moodle-theme_saylor#15]
WHY IS THE COURSE OVERVIEW SO GIANT

<img width="970" alt="screen shot 2017-05-08 at 4 17 51 pm" src="https://cloud.githubusercontent.com/assets/6720891/25823382/f436e01e-3409-11e7-92e9-e641e887cfd0.png">

**Comment by jazinheira** [comment]
So the course overview titles are set as h2, which are set to be larger. There are some line height options associated with the h2 headers.

<img width="1350" alt="screen shot 2017-05-09 at 1 51 06 pm" src="https://cloud.githubusercontent.com/assets/6720891/25864797/bc570ed4-34be-11e7-84d8-4610c48d7148.png">

**Comment by sharmi55** [comment]
This is no longer an issue as we have moved to using the plugin.
