### ISSUE TITLE
Update answer choice input fields when adding new multiple-choice questions

### ISSUE THREAD

**Issue by athuggins** [saylordotorg/moodle-theme_saylor#158]
When adding new multiple-choice questions (and possibly other question types, as well), it can be difficult to review questions at a glance without manually manipulating the size of the text input boxes, especially when answers or feedback contain more than one line of text. If possible, it would be nice to have an alternating background color for each answer choice (Choice X, Grade, and Feedback), so it's easy to ID at a glance which text fields correspond to which answer choice. It would also be helpful to set the default size of the text input fields to be 2 lines instead of 1, so you can see larger amounts of text without manually manipulating the size of the text box.

![screen shot 2019-01-28 at 12 49 58 pm](https://user-images.githubusercontent.com/4674292/51865987-90ec0280-22fc-11e9-8f71-395b2a3b6f30.png)

**Comment by jazinheira** [comment]
Fixed #176
