### ISSUE TITLE
Add message to dashboard when not enrolled in any courses

### ISSUE THREAD

**Issue by jazinheira** [saylordotorg/moodle-theme_saylor#16]
Let's add a message to display in the dashboard above the course overview if the student is not enrolled in any courses. Currently, the dashboard is blank when this is the case - it's confusing for new students when they get dumped on an empty page.

Maybe we can have a message encouraging them to add a course and a quick description on how to do so. @sharmi55 thoughts?

**Comment by sharmi55** [comment]
- Ideally, the user will not need to have an explanation on how to add a course if we fix the flow.

- Agree about having an encouraging message: "Start learning" which can be a link to the course catalog where each course has a clear "add a course" button

**Comment by jazinheira** [comment]
Fixed by moving to sayloroverview block in the dashboard.
