### ISSUE TITLE
OAuth button location

### ISSUE THREAD

**Issue by neonacorns** [saylordotorg/moodle-theme_saylor#173]
Bumping #81 since theme has been updated. OAuth button placement is non-obvious for subsequent login and is buried below new account information on mobile.

Generates lower-volume but consistent support tickets.

**Comment by jazinheira** [comment]
@neonacorns Do you know if this happening more consistently when the user is on mobile or desktop?

Are these new users and this is their first log in attempt? Are they older users returning (who forgot that they signed up with oauth)?

**Comment by jazinheira** [comment]
@neonacorns I'm not sure if this will actually help - people tend to forgot that they used oauth in the first place.

@rpmcdonnell What do you think about this layout?
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/6720891/55495009-f664b400-5609-11e9-89c9-021a51ed0e68.png">

**Comment by jazinheira** [comment]
From @neonacorns : "No data on desktop vs. mobile; yes to returning users -- sometimes just after a few hours or a day, usually after a few days to a week or more. They forget they signed up with OAuth and fail to sign in using a known password. Sometimes they do a pw reset"

**Comment by rpmcdonnell** [comment]
I think the layout works, has symmetry and a more clear differentiation between new and returning. Seems to follow along with the guidelines for buttons and whatnot as well

**Comment by jazinheira** [comment]
@rpmcdonnell Fixed the top spacing on the columns:

![image](https://user-images.githubusercontent.com/6720891/55558890-05576f00-56bb-11e9-8238-d086cf165910.png)

**Comment by jazinheira** [comment]
Fixed in #174
