### ISSUE TITLE
Remove "completed courses" from dashboard if none were completed

### ISSUE THREAD

**Issue by sharmi55** [saylordotorg/moodle-theme_saylor#18]
Hide "completed courses" if none were completed so as not to confuse the user.

![screen shot 2017-05-09 at 4 23 35 pm](https://cloud.githubusercontent.com/assets/16823841/25871016/12b76570-34d4-11e7-86c1-7f7234c7f0c7.png)

**Comment by jazinheira** [comment]
Fixed by moving to sayloroverview block in the dashboard.
