### ISSUE TITLE
Prettyprint clash with new style

### ISSUE THREAD

**Issue by athuggins** [saylordotorg/moodle-theme_saylor#180]
With the new theme, it can be difficult to read < pre > or < code > with the "prettyprint" class: 

![Screen Shot 2019-04-19 at 10 12 13 AM](https://user-images.githubusercontent.com/4674292/56434993-b1888080-628b-11e9-8fc0-d947c6ee7289.png)

Might be better to switch to a Solarized Light theme, or something similar.

**Comment by jazinheira** [comment]
Fixed #187
