### ISSUE TITLE
Add search box at top of nav bar

### ISSUE THREAD

**Issue by sharmi55** [saylordotorg/moodle-theme_saylor#19]
Similar to our peers, add search box at the top for users who prefer navigating that way.

![screen shot 2017-05-09 at 5 09 00 pm](https://cloud.githubusercontent.com/assets/16823841/25872944/812cc1de-34da-11e7-8d87-a2293dabe232.png)

**Comment by jazinheira** [comment]
@rpmcdonnell So you're away of this.

Do we still want a search function? What would it search - only courses? - and what would the benefits be? We already have the course search box in the catalog, so would having something in the nav bar just be wasting space?
