### ISSUE TITLE
Active link in course catalog shows a white background

### ISSUE THREAD

**Issue by dta121** [saylordotorg/moodle-theme_saylor#217]
I don't know if this is an issue, but when I click the course or the info icon, it shows a white active background. It normally wouldn't bother me, but it doesn't do that elsewhere. Like the side menu, the text background doesn't turn white.
![image](https://user-images.githubusercontent.com/74207428/98830368-f476ef80-23ff-11eb-86eb-caff15eb2ef7.png)

**Comment by jazinheira** [comment]
This is a recent regression and shouldn't happen because you are right, it doesn't happen elsewhere.
