### ISSUE TITLE
fix background and blocks color

### ISSUE THREAD

**Issue by sharmi55** [saylordotorg/moodle-theme_saylor#22]
Fix color so white is for the blocks and dark shade for main background.

![screen shot 2017-05-10 at 11 07 22 am](https://cloud.githubusercontent.com/assets/16823841/25906050/a8ed7a50-3571-11e7-868e-38f401879bbe.png)

**Comment by jazinheira** [comment]
Don't think we should be changing the colors right now, if we'll be doing that soon for the new theme. I did notice something got rolled into production so the nav blocks background becomes white on smaller screens (like a phone size width). Something in a media query.
