### ISSUE TITLE
Links in Sidebar

### ISSUE THREAD

**Issue by dta121** [saylordotorg/moodle-theme_saylor#222]
This may be personal preference but when I'm in a course, the links on the front page seem to blend in with the course navigation. Would it make it easier to distinguish between the two by having a space between the end? Like creating a new block, placing those links in the block, and then placing the block at the bottom.
![image](https://user-images.githubusercontent.com/74207428/98975715-10e85a00-24dc-11eb-8f3c-19b89b00d4c7.png)

**Comment by jazinheira** [comment]
I agree - pretty sure it used to be that way! Let's see what we can do to restore that.

**Comment by jazinheira** [comment]
Figured it out: it's the boostnavigation plugin. Specifically, disabling the dashboard nav button.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/6720891/116602415-b14f0100-a8f9-11eb-9876-7b1f70b968ad.png">

**Comment by jazinheira** [comment]
Fixed #262
