### ISSUE TITLE
M310 - Theme Issue

### ISSUE THREAD

**Issue by dta121** [saylordotorg/moodle-theme_saylor#226]
Taking a look at 3.10 on my desktop and when I applied the Saylor theme, there's were issues. The top logo did resize correct, color border in the nav bar is gone, color buttons, and the blocks overflow into the footer. Something to look at and fix before upgrading.
![image](https://user-images.githubusercontent.com/74207428/99682616-07637280-2a45-11eb-8331-c2c9970a199d.png)

**Comment by jazinheira** [comment]
@dta121 Double check that the theme's CSS styling is applying? Looks like 0 of the theme's CSS is there. Make sure to purge all caches, then use the inspector to browse through the loaded CSS for the page...

**Comment by dta121** [comment]
Yeah default.scss is loaded but none of the styling is coming through. Purged the caches as well. Doesn't look like any of the class/id changed.
