### ISSUE TITLE
Remove container above breadcrumbs

### ISSUE THREAD

**Issue by sharmi55** [saylordotorg/moodle-theme_saylor#23]
Breadcrumbs should either be removed or height needs to be diminished.
Remove from mobile version to save space.

![screen shot 2017-05-10 at 11 34 37 am](https://cloud.githubusercontent.com/assets/16823841/25907198/cb88281e-3574-11e7-88a6-9d298a812c3f.png)

**Comment by jazinheira** [comment]
We do need to save vertical space, but isn't that problem solved in the boost redesign? Do we want to wait for that?

**Comment by sharmi55** [comment]
yup, that's why I didn't attach it to the boost project but I thought it would be a good idea to put it up on Github as a quick fix.

**Comment by jazinheira** [comment]
I think we should leave the breadcrumbs if we take away the giant header!
