### ISSUE TITLE
Skipped Headers

### ISSUE THREAD

**Issue by dta121** [saylordotorg/moodle-theme_saylor#231]
Title levels should not be skipped and should be built with consistent hierarchy. For example: you cannot have "h4" titles and
"h2" titles without having "h3" titles.

Failed element:
`<h1></h1>`

**Comment by jazinheira** [comment]
Link to a specific page this is an issue (so we are able to test consistently)?

**Comment by dta121** [comment]
Yeah it's the course catalog of the main page: https://learn.saylor.org/
