### ISSUE TITLE
Assessment text input box missing border

### ISSUE THREAD

**Issue by neonacorns** [saylordotorg/moodle-theme_saylor#240]
See e.g. BUS205 Unit 2 Assessment Question 5. The text input box does not have a visible border.

![text-box](https://user-images.githubusercontent.com/10980346/106073214-781ab100-60be-11eb-93ae-3218c41ebf91.gif)

**Comment by dta121** [comment]
@neonacorns I added code that'll display the missing border in the assessment text box. The changes should appear in 3.10.
