### ISSUE TITLE
Redesign course summary

### ISSUE THREAD

**Issue by jazinheira** [saylordotorg/moodle-theme_saylor#25]
In the course catalog, we have a "summary" icon we can click to view more info about a course.

1) This summary should either always show or it should be clearer that there is more info and it can be expanded.

2) We should have other info about the course in there: cost, time commitment, etc.

3) There's an empty box on the left of the course summary - if we don't use this for the course info or something, we should remove it so the summary uses all available space and reflows better.

<img width="1285" alt="screen shot 2017-05-10 at 2 28 15 pm" src="https://cloud.githubusercontent.com/assets/6720891/25914929/d72a918e-358d-11e7-9486-870c133169be.png">

**Comment by sharmi55** [comment]
Hm.. I thought I had removed those useless icons...

**Comment by jazinheira** [comment]
Not in the new boost redesign!

**Comment by jazinheira** [comment]
Fixed in new design.
