### ISSUE TITLE
Suggestion to change button colors within activity/resource and button to navigate between activity/resource

### ISSUE THREAD

**Issue by dta121** [saylordotorg/moodle-theme_saylor#267]
I want to suggest a color change for the navigation buttons within an activity/resource to distinguish it from the button that navigates between resource/activity. Currently, they are the same color and in the same region of the page. It can look confusing for those who aren't familiar with the feature.
![image](https://user-images.githubusercontent.com/74207428/121725902-7838ad80-caaf-11eb-8add-3515d66fb9a3.png)

**Comment by jazinheira** [comment]
I also noticed a UX issue with the Moodle book resources - users are getting confused which button handles going to the next page (though those buttons don't look like our usual buttons).

**Comment by jazinheira** [comment]
Updated in books and quiz navigation so far. Next up is lessons.
