### ISSUE TITLE
Course Catalog

### ISSUE THREAD

**Issue by jazinheira** [saylordotorg/moodle-theme_saylor#27]
Let's brainstorm a course catalog - what do want to see? How can we make it more engaging? What information do students want to be able to easily see about the course directly?

@davidthompson89 Do you mind doing some mockups?

**Comment by jazinheira** [comment]
Similar (if not the same) to #25

**Comment by davidthompson89** [comment]
![course catalog mock up with icons](https://cloud.githubusercontent.com/assets/16214347/26126099/5e2369cc-3a52-11e7-841e-5ef8107bdb9c.jpg)

**Comment by davidthompson89** [comment]
![course catalog mock up with icons](https://cloud.githubusercontent.com/assets/16214347/26126239/dc500e7c-3a52-11e7-937b-fd07c2845122.jpg)

**Comment by jazinheira** [comment]
@rpmcdonnell Any other ideas for catalogs? Maybe a card based system, similar to how to the new 3.6 dashboard looks?
