### ISSUE TITLE
Questionnaire - Blue outline box on alert

### ISSUE THREAD

**Issue by jazinheira** [saylordotorg/moodle-theme_saylor#296]
![image](https://user-images.githubusercontent.com/6720891/136089385-05d742ec-36e1-49fd-a972-18c3d0c2bfc9.png)

#page-mod-questionnaire-complete .message, #page-mod-questionnaire-preview .message, #page-mod-questionnaire-complete .thankbody, #page-mod-questionnaire-complete .thankhead {
    border-color: blue;
}

* set border to none!

**Comment by dta121** [comment]
This looks good from my end!
