### ISSUE TITLE
New Typeface?

### ISSUE THREAD

**Issue by jazinheira** [saylordotorg/moodle-theme_saylor#30]
What are peoples' (@davidthompsion89 @sharmi55) thoughts on a new typeface (or, ideally, two to complement each other in headers/content).

We currently ONLY use Lato:
https://fonts.google.com/specimen/Lato

Wordpress's Twenty Seventeen is using Libre Franklin:
https://fonts.google.com/specimen/Libre+Franklin

Google has pushed Roboto into a lot of projects, including Android (designed for small screen legibility):
https://fonts.google.com/specimen/Roboto

Google Fonts has suggested Open Sans as a popular pairing for, well, all of these and it does seem to be easily readable. Seems like a good typeface for regular content.
https://fonts.google.com/specimen/Open+Sans

**Comment by sharmi55** [comment]
@davidthompsion89 and @jazinheira I think change is always good.

I suggest we should choose 2 and stick to the same in both WP and Learn.
I suggest Open Sans and Roboto but not a dealbreaker if you guys choose otherwise.

@neonacorns What do you think?

**Comment by jazinheira** [comment]
This site shows some combinations in use: https://fontsinuse.com/typefaces/7520/open-sans

**Comment by neonacorns** [comment]
That pairing seems okay. **Roboto Slab** can also be nice for headings/headers, for a little more differentiation between the two.

In Google Fonts you can play with size and swapping heading/paragraph fonts at the bottom of the page and see exactly what you'll get: https://fonts.google.com/specimen/Roboto+Slab

**Comment by neonacorns** [comment]
For quick reference (note that spacing and size are not great) here is a course home page with Roboto/Open-Sans and Roboto-Slab/Open-Sans...

![robot slab and open sans](https://user-images.githubusercontent.com/10980346/29476933-32e8f39a-8434-11e7-8308-eaac4cbb8305.png)
![roboto and open sans](https://user-images.githubusercontent.com/10980346/29476932-32e6e708-8434-11e7-8b1d-9bcfc39f1c71.png)

**Comment by jazinheira** [comment]
New typefaces are
