### ISSUE TITLE
Coderunner - Alert after failed check

### ISSUE THREAD

**Issue by jazinheira** [saylordotorg/moodle-theme_saylor#302]
It doesn't look good...

![image](https://user-images.githubusercontent.com/6720891/136105557-0b215ae4-bb1d-44d8-8b07-c27df2dc5bd5.png)

.que .outcome, .que .comment {
    color: #937300; 
    background-color: #fef3cc; 
    border-color: #fdeeb8; 
}

.que.coderunner div.coderunner-test-results.bad, .que.coderunner div.pre_syntax_error, .que.coderunner div.pre_question_error {
    background-color: #faa;
}

**Comment by dta121** [comment]
For some reason I can't find an example of color #937300 but everything else looks ok.
