### ISSUE TITLE
Hypens on Page Titles

### ISSUE THREAD

**Issue by nate-thompson** [saylordotorg/moodle-theme_saylor#33]
Please remove hyphens on either side of all titles

![image](https://cloud.githubusercontent.com/assets/10467391/26468883/079d38c4-4166-11e7-8a56-05e7f93dab2e.png)

**Comment by sharmi55** [comment]
Issue solved and on development branch now.
<img width="805" alt="screen shot 2017-07-05 at 2 54 33 pm" src="https://user-images.githubusercontent.com/16823841/27880124-dfcdd1ae-6191-11e7-805b-cbf8856a7248.png">
