### ISSUE TITLE
Have last accessed course by student be at the top of course list in dashboard

### ISSUE THREAD

**Issue by sharmi55** [saylordotorg/moodle-theme_saylor#35]
John suggested this feature at the end of the Brainstorming meeting

**Comment by jazinheira** [comment]
I really meant that we could organize the "In Progress" courses on the dashboard by order of last access - so the course the student was last in would be at the top of their course list.

**Comment by sharmi55** [comment]
This issue was solved in another repo:
https://github.com/saylordotorg/moodle-block_sayloroverview/commit/4eaaa74ad1d3964714ae2041ef43b4109ec8dcc0
