### ISSUE TITLE
Remove site pages link from left nav bar along with sublinks

### ISSUE THREAD

**Issue by sharmi55** [saylordotorg/moodle-theme_saylor#36]
<img width="264" alt="screen shot 2017-06-06 at 5 03 46 pm" src="https://user-images.githubusercontent.com/16823841/26852010-b3dfe3d4-4ada-11e7-9d22-941a86addf54.png">

**Comment by neonacorns** [comment]
It's an old thread, but it looks like CSS hacks would be one approach; something _like_ this:

`/* Remove "Site Pages" */
.block_navigation .type_course.depth_2  { display: none; }`

via https://webcache.googleusercontent.com/search?q=cache:meOjY0trgiUJ:https://moodle.org/mod/forum/discuss.php%3Fd%3D180982+&cd=3&hl=en&ct=clnk&gl=us

**Comment by jazinheira** [comment]
Yeah, we should do a quick 'n dirty CSS hack for this... for now.

**Comment by sharmi55** [comment]
Yup, will be doing exactly that!
