### ISSUE TITLE
Remove My Courses from left nav bar 

### ISSUE THREAD

**Issue by sharmi55** [saylordotorg/moodle-theme_saylor#37]
<img width="320" alt="screen shot 2017-06-06 at 5 11 00 pm" src="https://user-images.githubusercontent.com/16823841/26852119-306adc06-4adb-11e7-9ce7-03174b37c3c9.png">

**Comment by sharmi55** [comment]
"My courses" has been removed from left nav bar while still keeping child element "Courses". However there is a problem with the height as shown on the screencaps.

<img width="352" alt="screen shot 2017-06-15 at 4 53 14 pm" src="https://user-images.githubusercontent.com/16823841/27201347-591c6b62-51eb-11e7-979c-270c0f44d4d9.png">


<img width="303" alt="screen shot 2017-06-15 at 4 53 21 pm" src="https://user-images.githubusercontent.com/16823841/27201351-5cd96200-51eb-11e7-94d0-271c5fec9d8d.png">

**Comment by jazinheira** [comment]
Tested and unfortunately doesn't work on Firefox at all; both end up being hidden. We can remove both or none at all...

**Comment by sharmi55** [comment]
yes, agreed. The html code does not allow for hiding only the "My Courses" bit as I explained three weeks ago.
