### ISSUE TITLE
Update "enrollment" boilerplate in syllabi via command line

### ISSUE THREAD

**Issue by neonacorns** [saylordotorg/moodle-theme_saylor#38]
Recommend changing:
"...using the “Enroll me in this course” button located on the left hand toolbar."

to:
"...using the "Enroll me in this course" link in the Administration area on the left side of the screen (desktop) or bottom of the page (mobile)."

There is a command line search and replace tool that updates the database: [https://docs.moodle.org/33/en/Administration_via_command_line#Search_and_replace_text](https://docs.moodle.org/33/en/Administration_via_command_line#Search_and_replace_text)

Rationale is that, for the next many weeks, "link" is more accurate than "button", and the administration area is not necessarily on the left side of the screen.

**Comment by jazinheira** [comment]
@sharmi55 @neonacorns  I know that we've updated the course syllabi language recently - was this part of that update?

**Comment by jazinheira** [comment]
@neonacorns Is this issue still accurate? Or did we already update that language? @athuggins Do you know if we updated the syllabus template with that language?
