### ISSUE TITLE
Fix Navigation Block

### ISSUE THREAD

**Issue by DevonRitter** [saylordotorg/moodle-theme_saylor#44]
Overall Goal - Have a navigation block that is clear, usable, and which reduces redundancies.

Ideals:

When Users are **not** logged in (Note: When not logged in, users only see Nav Block once they are within a course):
- Home
- Current Course
- Courses (Collapsed, but expandable with list of all Saylor Courses, grouped by Course Category)
- Things to be removed from view: Site Pages; Participants (which shows up in an expanded course nav)

When Users are signed in, but not yet in a course:
- Dashboard
- Site Home
- My Courses (Expanded by default to show list of courses, but not to expand each course nav)
- Courses (Collapsed, but expandable with list of all Saylor Courses, grouped by Course Category)
- Things to be removed from view: Site Pages; Participants (which shows up in an expanded course nav)

When Users are signed in, **and** viewing a course:
Dashboard
Site Home
Current Course
My Courses (Collapsed, but expandable to show all currently enrolled courses)
Courses (Collapsed, but expandable with list of all Saylor Courses, grouped by Course Category)
Things to be removed from view: Site Pages; Participants (which shows up in an expanded course nav)

Relates Issues:
- https://github.com/saylordotorg/moodle-theme_saylor/issues/36
- https://github.com/saylordotorg/moodle-theme_saylor/issues/37

![pre-update nav bar](https://user-images.githubusercontent.com/2089910/27879866-e4ef1d06-6177-11e7-9b79-0e01f369835c.png)

Image Above generally shows what the ideal would be when students are logged in and viewing a course, with the exception that we want "site pages" to be removed.

**Comment by sharmi55** [comment]
@davidthompson89 something to consider while we create Boost mockups.
