### ISSUE TITLE
Dashboard courses order 

### ISSUE THREAD

**Issue by sharmi55** [saylordotorg/moodle-theme_saylor#46]
Show course order from the most recently accessed or the most recently enrolled into instead of long list.

Here is a mock up of what courses could look like:

<img width="406" alt="screen shot 2017-07-11 at 2 07 36 pm" src="https://user-images.githubusercontent.com/16823841/28083115-5e3801c2-6642-11e7-8b30-bafde6c14e52.png">

**Comment by jazinheira** [comment]
Fixed
