### ISSUE TITLE
Have identical log in status message in learn and wordpress websites

### ISSUE THREAD

**Issue by sharmi55** [saylordotorg/moodle-theme_saylor#56]
We should have identical wording for the top right login portal when user is not logged in.

This is how it is now:
saylor.org
<img width="121" alt="screen shot 2017-07-28 at 1 09 59 pm" src="https://user-images.githubusercontent.com/16823841/28728301-197cd664-7396-11e7-85c3-a5b600332a7c.png">
learn.saylor.org
<img width="162" alt="screen shot 2017-07-28 at 1 09 48 pm" src="https://user-images.githubusercontent.com/16823841/28728308-1f929bec-7396-11e7-9712-2c583a371f64.png">

I propose we go with "Log In or Sign Up". 
Maybe debate about whether to keep the lock icon or not.

**Comment by jazinheira** [comment]
1) Remove the lock icon - that signifies locking the account and is going to confuse people. Makes more sense for log out

2) We can update to "Log in or Sign up" - the page handles both so I'm ok with that.

3) We should be careful about the capitalization, ie "Log in", just so everything jives with the Moodle standard.

**Comment by sharmi55** [comment]
Ok @jazinheira , I will make the necessary changes in both learn and WP to the language.

Log in or Sign Up is the only thing on should see on top right.

**Comment by sharmi55** [comment]
jazinheira, I have changed status log in message in Learn and WP:

Learn:
<img width="422" alt="screen shot 2017-08-08 at 4 15 42 pm" src="https://user-images.githubusercontent.com/16823841/29093605-5eaefc92-7c58-11e7-956e-726ac04c9ec8.png">

WP:
<img width="368" alt="screen shot 2017-08-08 at 4 42 44 pm" src="https://user-images.githubusercontent.com/16823841/29093689-a8a49262-7c58-11e7-8b8a-d2b2376d9243.png">
