### ISSUE TITLE
Add landing page after completing final exam to track data

### ISSUE THREAD

**Issue by sharmi55** [saylordotorg/moodle-theme_saylor#60]
Request by Zack:
"To have a landing page after people complete the final so that we can stick the course eval there and so that I can track that page on GA."

**Comment by jazinheira** [comment]
Looks like users are redirected directly to a quiz review: https://learn.saylor.org/mod/quiz/review.php

Users can look at review previous attempts, so if they did just take the quiz, the previous pages would be:
https://learn.saylor.org/mod/quiz/attempt.php ->
https://learn.saylor.org/mod/quiz/summary.php ->
https://learn.saylor.org/mod/quiz/review.php
