### ISSUE TITLE
Make course titles less prominent

### ISSUE THREAD

**Issue by neonacorns** [saylordotorg/moodle-theme_saylor#62]
I realize this might happen anyway with new theming, but consider making course titles less dominant throughout. For example, course title could appear on the course front page in the main content area and not on subsequent course pages.

**Title page**
![title 1](https://user-images.githubusercontent.com/10980346/30074104-30161018-923e-11e7-9767-089a57df2f3d.png)

-----
**Deeper course page**
![title 2](https://user-images.githubusercontent.com/10980346/30074039-f1ff01c2-923d-11e7-900f-06030aca46a0.png)

**Comment by jazinheira** [comment]
Fixed in new theme.
