### ISSUE TITLE
Log in / sign up spacing 

### ISSUE THREAD

**Issue by neonacorns** [saylordotorg/moodle-theme_saylor#63]
Could use more spacing between "log in or sign up" CTA and the "back to..." link on unit and sub-unit pages:

![spacing](https://user-images.githubusercontent.com/10980346/30276654-855ce4ae-96d3-11e7-8f6e-55eda52252be.png)

**Comment by neonacorns** [comment]
n.b. spacing seems okay for the button (i.e. when logged in):

![spacing 2](https://user-images.githubusercontent.com/10980346/30282696-079bde42-96e4-11e7-9b47-2e3350b38561.png)

**Comment by jazinheira** [comment]
Fixed in PR #64 
<img width="936" alt="screen shot 2017-10-19 at 2 16 27 pm" src="https://user-images.githubusercontent.com/6720891/31786944-26b14044-b4d8-11e7-956d-46d8ba43af86.png">
