### ISSUE TITLE
OAuth placement

### ISSUE THREAD

**Issue by neonacorns** [saylordotorg/moodle-theme_saylor#81]
OAuth buttons display only in the "sign up" area, which can lead to confusion for users who are trying to sign in to an existing oauth-connected account (presumably the users do not notice the oauth buttons when trying to sign in again).

E.g. user is unable to sign in and needs help retrieving a password, but the user actually signed up using oauth and should use that method to authenticate.

The issue is more pronounced in the mobile view, where the oauth buttons would be off screen and more distant from the sign in area.

![oauth](https://user-images.githubusercontent.com/10980346/33838570-e56fec02-de5d-11e7-8ee6-326c9ba296cc.png)

**Comment by jazinheira** [comment]
In boost based themes it seems the templating system is more malleable and is in a better spot by default. Unfortunately, I'm unable to move these in our current theme; we'll have to wait until the move to the new theme.
