### ISSUE TITLE
"My Courses" Shows Completed Courses

### ISSUE THREAD

**Issue by jazinheira** [saylordotorg/moodle-theme_saylor#9]
In the "My Courses" menu on the left column, all enrolled courses are shown. This should only be active (non-completed) courses; we can use logic similar to the dashboard renderer.

@sharmi55 do you think we should also rename "My Courses" to something else (if possible)?
<img width="311" alt="screen shot 2017-05-08 at 3 58 08 pm" src="https://cloud.githubusercontent.com/assets/6720891/25822639/3b3c10c2-3407-11e7-8cc7-2e05003c1ad4.png">

**Comment by sharmi55** [comment]
Hm..I'll look into it and think about possible ideas to replace wording in general.

**Comment by jazinheira** [comment]
Fixed
